{
 "title": "Evmos Testnet",
 "description": "A Grafana dashboard compatible with all the cosmos-sdk and tendermint based blockchains.",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(tendermint_consensus_height, chain_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$chain_id overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current price in USD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "coin_market_price_usd{id=\"evmos\",instance=\"coinmarketcap-exporter:9101\",job=\"coinmarketcap\",name=\"Evmos\",symbol=\"EVMOS\"}"
    }
   ]
  },
  {
   "title": "Current price in USD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "USD" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{id=\"evmos\",instance=\"coinmarketcap-exporter:9101\",job=\"coinmarketcap\",name=\"Evmos\",symbol=\"EVMOS\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 6 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 6 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum/tendermint_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Feemarket base fee",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feemarket_base_fee{chain_id=\"evmos_9000-4\", instance=\"34.134.223.153:1317\", job=\"evmos-telemetry\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Feemarket block gas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "feemarket_block_gas{chain_id=\"evmos_9000-4\", instance=\"34.134.223.153:1317\", job=\"evmos-telemetry\"}"
    }
   ]
  },
  {
   "title": "EVM tx total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tx_msg_ethereum_tx_total{job=\"evmos-telemetry\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Gas used total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tx_msg_ethereum_tx_gas_used_total{job=\"evmos-telemetry\"}[$__range]))"
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Unconfirmed Transactions",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Failed Transactions",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Recheck Times",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total Network Input",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tendermint_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total Network Output",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tendermint_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  }
 ]
}